import type { Domain } from "@/lib/analysis/domains";

export interface MetricDefinition {
  id: string;
  domain: Domain;
  name: string;
  shortName: string;
  description: string;
  unit: string;
  unitLabel: string;
  source: "wearable" | "chess_api" | "lichess_api" | "manual";
  inputType?: "slider" | "number" | "time" | "toggle" | "stepper" | "text";
  inputConfig?: {
    min?: number;
    max?: number;
    step?: number;
    placeholder?: string;
  };
  format: (value: number) => string;
  healthyRange?: { min: number; max: number; label: string };
  availableDevices?: string[];
  detectorIds: string[];
}

// ── Format helpers ────────────────────────────────────────────────────────────

const fmtHours   = (v: number) => `${v.toFixed(1)} hrs`;
const fmtPct     = (v: number) => `${Math.round(v)}%`;
const fmtMinutes = (v: number) => `${Math.round(v)} min`;
const fmtCount   = (v: number) => `${Math.round(v)}`;
const fmtBpm     = (v: number) => `${Math.round(v)} bpm`;
const fmtMs      = (v: number) => `${Math.round(v)} ms`;
const fmtElo     = (v: number) => `${Math.round(v)}`;
const fmtMg      = (v: number) => `${Math.round(v)} mg`;
const fmtLitres  = (v: number) => `${v.toFixed(1)} L`;
const fmtSlash10 = (v: number) => `${Math.round(v)}/10`;
const fmtKcal    = (v: number) => `${Math.round(v)} kcal`;
const fmtSteps   = (v: number) => `${Math.round(v).toLocaleString()}`;
const fmtPerGame = (v: number) => `${v.toFixed(1)}/game`;

function fmtTime(v: number): string {
  const h24 = Math.floor(v) % 24;
  const mins = Math.round((v % 1) * 60);
  const ampm = h24 >= 12 ? "PM" : "AM";
  const h12 = h24 % 12 || 12;
  return `${h12}:${String(mins).padStart(2, "0")} ${ampm}`;
}

// ── Sleep Metrics (14) ────────────────────────────────────────────────────────

const SLEEP_METRICS: MetricDefinition[] = [
  {
    id: "sleep_total_duration",
    domain: "sleep",
    name: "Total Sleep Duration",
    shortName: "Sleep Duration",
    description: "Total time asleep per night",
    unit: "hours",
    unitLabel: "hrs",
    source: "wearable",
    format: fmtHours,
    healthyRange: { min: 7, max: 9, label: "7-9 hours recommended" },
    availableDevices: ["Garmin", "Fitbit", "Apple Health", "Oura", "Whoop"],
    detectorIds: [
      "SLEEP_DURATION_STAT",
      "SLEEP_DURATION_TREND",
      "SLEEP_DEBT_ACCUMULATION",
      "WEEKEND_SLEEP_SHIFT",
      "SLEEP_EFFICIENCY",
      "DEEP_SLEEP_RATIO",
      "SLEEP_PERFORMANCE_CORRELATION",
      "SLEEP_QUALITY_CORRELATION",
      "REST_DAY_SLEEP_QUALITY",
      "MORNING_VS_EVENING_WORKOUT_SLEEP",
      "OVERTRAINING_SLEEP_SIGNAL",
      "STEP_COUNT_VS_SLEEP_DEPTH",
      "MOOD_SLEEP_CORRELATION",
      "STRESS_SLEEP_CORRELATION",
      "CHESS_SLEEP_CORRELATION",
      "SLEEP_DURATION_VS_CHESS_ACCURACY",
      "LATE_NIGHT_CHESS_VS_NEXT_SLEEP",
    ],
  },
  {
    id: "sleep_efficiency",
    domain: "sleep",
    name: "Sleep Efficiency",
    shortName: "Efficiency",
    description: "Percentage of time in bed actually spent sleeping",
    unit: "%",
    unitLabel: "%",
    source: "wearable",
    format: fmtPct,
    healthyRange: { min: 85, max: 100, label: "85%+ is healthy" },
    availableDevices: ["Garmin", "Fitbit", "Apple Health", "Oura", "Whoop"],
    detectorIds: ["SLEEP_EFFICIENCY"],
  },
  {
    id: "sleep_deep_duration",
    domain: "sleep",
    name: "Deep Sleep Duration",
    shortName: "Deep Sleep",
    description: "Time spent in N3 deep sleep stage",
    unit: "hours",
    unitLabel: "hrs",
    source: "wearable",
    format: fmtHours,
    availableDevices: ["Garmin", "Fitbit", "Apple Health", "Oura", "Whoop"],
    detectorIds: [
      "DEEP_SLEEP_RATIO",
      "SLEEP_QUALITY_CORRELATION",
      "REST_DAY_SLEEP_QUALITY",
      "STEP_COUNT_VS_SLEEP_DEPTH",
      "LATE_NIGHT_CHESS_VS_NEXT_SLEEP",
    ],
  },
  {
    id: "sleep_deep_pct",
    domain: "sleep",
    name: "Deep Sleep %",
    shortName: "Deep Sleep %",
    description: "Deep sleep as a percentage of total sleep",
    unit: "%",
    unitLabel: "%",
    source: "wearable",
    format: fmtPct,
    healthyRange: { min: 15, max: 25, label: "15-25% is typical" },
    availableDevices: ["Garmin", "Fitbit", "Apple Health", "Oura", "Whoop"],
    detectorIds: [
      "DEEP_SLEEP_RATIO",
      "SLEEP_QUALITY_CORRELATION",
      "REST_DAY_SLEEP_QUALITY",
      "STEP_COUNT_VS_SLEEP_DEPTH",
      "LATE_NIGHT_CHESS_VS_NEXT_SLEEP",
    ],
  },
  {
    id: "sleep_rem_duration",
    domain: "sleep",
    name: "REM Sleep Duration",
    shortName: "REM Sleep",
    description: "Time spent in REM sleep stage",
    unit: "hours",
    unitLabel: "hrs",
    source: "wearable",
    format: fmtHours,
    availableDevices: ["Garmin", "Fitbit", "Apple Health", "Oura", "Whoop"],
    detectorIds: ["SLEEP_QUALITY_CORRELATION"],
  },
  {
    id: "sleep_rem_pct",
    domain: "sleep",
    name: "REM Sleep %",
    shortName: "REM %",
    description: "REM sleep as a percentage of total sleep",
    unit: "%",
    unitLabel: "%",
    source: "wearable",
    format: fmtPct,
    healthyRange: { min: 20, max: 25, label: "20-25% is typical" },
    availableDevices: ["Garmin", "Fitbit", "Apple Health", "Oura", "Whoop"],
    detectorIds: ["SLEEP_QUALITY_CORRELATION"],
  },
  {
    id: "sleep_light_duration",
    domain: "sleep",
    name: "Light Sleep Duration",
    shortName: "Light Sleep",
    description: "Time spent in N1/N2 light sleep",
    unit: "hours",
    unitLabel: "hrs",
    source: "wearable",
    format: fmtHours,
    availableDevices: ["Garmin", "Fitbit", "Apple Health", "Oura", "Whoop"],
    detectorIds: [],
  },
  {
    id: "sleep_latency",
    domain: "sleep",
    name: "Sleep Latency",
    shortName: "Time to Sleep",
    description: "Time from getting in bed to falling asleep",
    unit: "minutes",
    unitLabel: "min",
    source: "wearable",
    format: fmtMinutes,
    healthyRange: { min: 5, max: 20, label: "5-20 min is normal" },
    availableDevices: ["Garmin", "Fitbit", "Apple Health", "Oura", "Whoop"],
    detectorIds: [],
  },
  {
    id: "sleep_wake_episodes",
    domain: "sleep",
    name: "Wake Episodes",
    shortName: "Wake Ups",
    description: "Number of times woken during the night",
    unit: "count",
    unitLabel: "times",
    source: "wearable",
    format: fmtCount,
    availableDevices: ["Garmin", "Fitbit", "Apple Health", "Oura", "Whoop"],
    detectorIds: ["SLEEP_EFFICIENCY", "OVERTRAINING_SLEEP_SIGNAL"],
  },
  {
    id: "sleep_bedtime",
    domain: "sleep",
    name: "Bedtime",
    shortName: "Bedtime",
    description: "Clock time when you went to bed",
    unit: "time",
    unitLabel: "—",
    source: "wearable",
    format: fmtTime,
    availableDevices: ["Garmin", "Fitbit", "Apple Health", "Oura", "Whoop"],
    detectorIds: [
      "BEDTIME_CONSISTENCY",
      "SLEEP_EFFICIENCY",
      "BEDTIME_ENERGY_CORRELATION",
      "LATE_NIGHT_CHESS_VS_NEXT_SLEEP",
    ],
  },
  {
    id: "sleep_wake_time",
    domain: "sleep",
    name: "Wake Time",
    shortName: "Wake Time",
    description: "Clock time when you woke up",
    unit: "time",
    unitLabel: "—",
    source: "wearable",
    format: fmtTime,
    availableDevices: ["Garmin", "Fitbit", "Apple Health", "Oura", "Whoop"],
    detectorIds: ["SLEEP_EFFICIENCY"],
  },
  {
    id: "sleep_resting_hr",
    domain: "sleep",
    name: "Resting Heart Rate (Sleep)",
    shortName: "Sleep HR",
    description: "Average heart rate during sleep",
    unit: "bpm",
    unitLabel: "bpm",
    source: "wearable",
    format: fmtBpm,
    availableDevices: ["Garmin", "Fitbit", "Apple Health", "Oura", "Whoop"],
    detectorIds: [],
  },
  {
    id: "sleep_hrv",
    domain: "sleep",
    name: "HRV (Sleep)",
    shortName: "Sleep HRV",
    description: "Heart rate variability measured during sleep",
    unit: "ms",
    unitLabel: "ms",
    source: "wearable",
    format: fmtMs,
    availableDevices: ["Garmin", "Fitbit", "Apple Health", "Oura", "Whoop"],
    detectorIds: ["HRV_DURING_SLEEP_TREND"],
  },
  {
    id: "sleep_spo2",
    domain: "sleep",
    name: "SpO2",
    shortName: "Blood Oxygen",
    description: "Average blood oxygen saturation during sleep",
    unit: "%",
    unitLabel: "%",
    source: "wearable",
    format: fmtPct,
    healthyRange: { min: 95, max: 100, label: "95%+ is normal" },
    availableDevices: ["Garmin", "Fitbit", "Apple Health", "Oura", "Whoop"],
    detectorIds: [],
  },
];

// ── Fitness Metrics (12) ──────────────────────────────────────────────────────

const FITNESS_METRICS: MetricDefinition[] = [
  {
    id: "fitness_workouts_per_week",
    domain: "fitness",
    name: "Workouts Per Week",
    shortName: "Workouts/Wk",
    description: "Number of structured workouts logged this week",
    unit: "count",
    unitLabel: "—",
    source: "wearable",
    format: fmtCount,
    availableDevices: ["Garmin", "Fitbit", "Apple Health"],
    detectorIds: [
      "WORKOUT_FREQUENCY_STAT",
      "WORKOUT_CONSISTENCY_PATTERN",
      "SLEEP_PERFORMANCE_CORRELATION",
      "SLEEP_QUALITY_CORRELATION",
      "REST_DAY_SLEEP_QUALITY",
      "MORNING_VS_EVENING_WORKOUT_SLEEP",
      "OVERTRAINING_SLEEP_SIGNAL",
      "ENERGY_WORKOUT_CORRELATION",
      "WORKOUT_STRESS_CORRELATION",
      "EXERCISE_MOOD_BOOST",
      "WORKOUT_INTENSITY_VS_NEXT_DAY_ENERGY",
      "CONSISTENCY_VS_MOOD_BASELINE",
      "CHESS_EXERCISE_CORRELATION",
      "WORKOUT_DAY_VS_CHESS_PERFORMANCE",
      "POST_WORKOUT_CHESS_TIMING",
    ],
  },
  {
    id: "fitness_active_minutes",
    domain: "fitness",
    name: "Active Minutes Per Day",
    shortName: "Active Min",
    description: "Minutes at elevated heart rate (moderate + vigorous)",
    unit: "minutes",
    unitLabel: "min",
    source: "wearable",
    format: fmtMinutes,
    healthyRange: { min: 21, max: 60, label: "150 min/week WHO target" },
    availableDevices: ["Garmin", "Fitbit", "Apple Health"],
    detectorIds: ["ACTIVE_MINUTES_VS_SEDENTARY"],
  },
  {
    id: "fitness_steps",
    domain: "fitness",
    name: "Steps Per Day",
    shortName: "Steps",
    description: "Daily step count",
    unit: "count",
    unitLabel: "steps",
    source: "wearable",
    format: fmtSteps,
    healthyRange: { min: 8000, max: 12000, label: "8,000-10,000+ recommended" },
    availableDevices: ["Garmin", "Fitbit", "Apple Health"],
    detectorIds: ["STEP_COUNT_VS_SLEEP_DEPTH"],
  },
  {
    id: "fitness_calories",
    domain: "fitness",
    name: "Calories Burned",
    shortName: "Calories",
    description: "Total daily energy expenditure",
    unit: "kcal",
    unitLabel: "kcal",
    source: "wearable",
    format: fmtKcal,
    availableDevices: ["Garmin", "Fitbit", "Apple Health"],
    detectorIds: ["PERSONAL_BESTS_FREQUENCY"],
  },
  {
    id: "fitness_avg_workout_hr",
    domain: "fitness",
    name: "Avg Workout Heart Rate",
    shortName: "Workout HR",
    description: "Average heart rate during workouts",
    unit: "bpm",
    unitLabel: "bpm",
    source: "wearable",
    format: fmtBpm,
    availableDevices: ["Garmin", "Fitbit", "Apple Health"],
    detectorIds: ["HEART_RATE_RECOVERY"],
  },
  {
    id: "fitness_max_hr",
    domain: "fitness",
    name: "Max Heart Rate (Workout)",
    shortName: "Max HR",
    description: "Peak heart rate reached during workouts",
    unit: "bpm",
    unitLabel: "bpm",
    source: "wearable",
    format: fmtBpm,
    availableDevices: ["Garmin", "Fitbit", "Apple Health"],
    detectorIds: [],
  },
  {
    id: "fitness_avg_workout_duration",
    domain: "fitness",
    name: "Avg Workout Duration",
    shortName: "Workout Len",
    description: "Average length of workout sessions",
    unit: "minutes",
    unitLabel: "min",
    source: "wearable",
    format: fmtMinutes,
    availableDevices: ["Garmin", "Fitbit", "Apple Health"],
    detectorIds: [
      "WORKOUT_DURATION_TREND",
      "WORKOUT_INTENSITY_VS_NEXT_DAY_ENERGY",
      "POST_WORKOUT_CHESS_TIMING",
      "PERSONAL_BESTS_FREQUENCY",
    ],
  },
  {
    id: "fitness_resting_hr",
    domain: "fitness",
    name: "Resting Heart Rate",
    shortName: "Resting HR",
    description: "Daily resting heart rate",
    unit: "bpm",
    unitLabel: "bpm",
    source: "wearable",
    format: fmtBpm,
    healthyRange: { min: 50, max: 70, label: "50-70 bpm for active adults" },
    availableDevices: ["Garmin", "Fitbit", "Apple Health"],
    detectorIds: ["RESTING_HR_TREND", "HEART_RATE_RECOVERY"],
  },
  {
    id: "fitness_hrv",
    domain: "fitness",
    name: "HRV (Daily)",
    shortName: "Daily HRV",
    description: "Daily heart rate variability measurement",
    unit: "ms",
    unitLabel: "ms",
    source: "wearable",
    format: fmtMs,
    availableDevices: ["Garmin", "Fitbit", "Apple Health", "Oura", "Whoop"],
    detectorIds: [],
  },
  {
    id: "fitness_workout_type_dist",
    domain: "fitness",
    name: "Workout Type Distribution",
    shortName: "Type Balance",
    description: "Breakdown of cardio vs strength vs flexibility",
    unit: "category",
    unitLabel: "—",
    source: "wearable",
    format: fmtCount,
    availableDevices: ["Garmin", "Fitbit", "Apple Health"],
    detectorIds: ["CARDIO_VS_STRENGTH_BALANCE"],
  },
  {
    id: "fitness_vo2max",
    domain: "fitness",
    name: "VO2 Max Estimate",
    shortName: "VO2 Max",
    description: "Estimated aerobic capacity",
    unit: "mL/kg/min",
    unitLabel: "mL/kg/min",
    source: "wearable",
    format: (v) => `${v.toFixed(1)} mL/kg/min`,
    availableDevices: ["Garmin", "Fitbit", "Apple Health"],
    detectorIds: [],
  },
  {
    id: "fitness_rest_days",
    domain: "fitness",
    name: "Rest Days Per Week",
    shortName: "Rest Days",
    description: "Days this week with no structured workout",
    unit: "count",
    unitLabel: "days",
    source: "wearable",
    format: fmtCount,
    availableDevices: ["Garmin", "Fitbit", "Apple Health"],
    detectorIds: ["REST_DAY_SLEEP_QUALITY"],
  },
];

// ── Chess Metrics (12) ────────────────────────────────────────────────────────

const CHESS_METRICS: MetricDefinition[] = [
  {
    id: "chess_rating",
    domain: "chess",
    name: "Rating",
    shortName: "Rating",
    description: "Current Elo rating by time control",
    unit: "elo",
    unitLabel: "—",
    source: "chess_api",
    format: fmtElo,
    detectorIds: [
      "CHESS_RATING_TREND_RAPID",
      "CHESS_RATING_TREND_BLITZ",
      "CHESS_RATING_TREND_BULLET",
      "RATING_VOLATILITY",
      "BLITZ_VS_RAPID_RATING_GAP",
      "CHESS_STRESS_CORRELATION",
      "WORKOUT_DAY_VS_CHESS_PERFORMANCE",
    ],
  },
  {
    id: "chess_accuracy",
    domain: "chess",
    name: "Accuracy",
    shortName: "Accuracy",
    description: "Average move accuracy per game",
    unit: "%",
    unitLabel: "%",
    source: "chess_api",
    format: fmtPct,
    detectorIds: [
      "ACCURACY_TREND",
      "CHESS_VOLUME_PERFORMANCE",
      "SLEEP_DURATION_VS_CHESS_ACCURACY",
      "CHESS_SLEEP_CORRELATION",
      "CHESS_ENERGY_CORRELATION",
      "WORKOUT_DAY_VS_CHESS_PERFORMANCE",
      "POST_WORKOUT_CHESS_TIMING",
    ],
  },
  {
    id: "chess_games_per_week",
    domain: "chess",
    name: "Games Per Week",
    shortName: "Games/Wk",
    description: "Number of games played this week",
    unit: "count",
    unitLabel: "—",
    source: "chess_api",
    format: fmtCount,
    detectorIds: [
      "CHESS_VOLUME_PERFORMANCE",
      "WIN_STREAK_PATTERNS",
      "CHESS_EXERCISE_CORRELATION",
    ],
  },
  {
    id: "chess_win_rate",
    domain: "chess",
    name: "Win Rate",
    shortName: "Win Rate",
    description: "Percentage of games won (rolling window)",
    unit: "%",
    unitLabel: "%",
    source: "chess_api",
    format: fmtPct,
    detectorIds: [
      "CHESS_TIME_OF_DAY",
      "CHESS_VOLUME_PERFORMANCE",
      "WIN_STREAK_PATTERNS",
      "TILT_DETECTION",
      "CHESS_MOOD_CORRELATION",
      "CHESS_STRESS_CORRELATION",
      "CHESS_ENERGY_CORRELATION",
      "CHESS_SLEEP_CORRELATION",
      "CHESS_LOSSES_VS_NEXT_DAY_MOOD",
      "CHESS_EXERCISE_CORRELATION",
      "WORKOUT_DAY_VS_CHESS_PERFORMANCE",
      "POST_WORKOUT_CHESS_TIMING",
    ],
  },
  {
    id: "chess_result_dist",
    domain: "chess",
    name: "Win/Draw/Loss Distribution",
    shortName: "Results",
    description: "Breakdown of game results",
    unit: "ratio",
    unitLabel: "—",
    source: "chess_api",
    format: fmtPct,
    detectorIds: [
      "CHESS_MOOD_CORRELATION",
      "CHESS_STRESS_CORRELATION",
      "CHESS_ENERGY_CORRELATION",
      "CHESS_SLEEP_CORRELATION",
      "CHESS_LOSSES_VS_NEXT_DAY_MOOD",
    ],
  },
  {
    id: "chess_avg_opponent",
    domain: "chess",
    name: "Avg Opponent Rating",
    shortName: "Opp. Rating",
    description: "Average rating of opponents faced",
    unit: "elo",
    unitLabel: "—",
    source: "chess_api",
    format: fmtElo,
    detectorIds: [],
  },
  {
    id: "chess_blunder_rate",
    domain: "chess",
    name: "Blunder Rate",
    shortName: "Blunders",
    description: "Average blunders per game",
    unit: "per game",
    unitLabel: "/game",
    source: "chess_api",
    format: fmtPerGame,
    detectorIds: [],
  },
  {
    id: "chess_time_of_day",
    domain: "chess",
    name: "Time of Day Played",
    shortName: "Play Time",
    description: "Typical clock time when games are played",
    unit: "hour",
    unitLabel: "—",
    source: "chess_api",
    format: fmtTime,
    detectorIds: [
      "CHESS_TIME_OF_DAY",
      "TIME_OF_DAY_PERFORMANCE",
      "CHESS_VOLUME_PERFORMANCE",
      "LATE_NIGHT_CHESS_VS_NEXT_SLEEP",
      "STRESS_VS_CHESS_TILT",
      "POST_WORKOUT_CHESS_TIMING",
    ],
  },
  {
    id: "chess_game_length",
    domain: "chess",
    name: "Game Duration (Moves)",
    shortName: "Game Length",
    description: "Average number of moves per game",
    unit: "count",
    unitLabel: "moves",
    source: "chess_api",
    format: fmtCount,
    detectorIds: ["GAME_LENGTH_PREFERENCE"],
  },
  {
    id: "chess_opening",
    domain: "chess",
    name: "Opening Played",
    shortName: "Opening",
    description: "Most frequently played openings",
    unit: "name",
    unitLabel: "—",
    source: "chess_api",
    format: fmtCount,
    detectorIds: ["OPENING_REPERTOIRE_DIVERSITY", "MOOD_VS_CHESS_RISK_TAKING"],
  },
  {
    id: "chess_time_control",
    domain: "chess",
    name: "Time Control",
    shortName: "Format",
    description: "Bullet, blitz, rapid, or classical",
    unit: "category",
    unitLabel: "—",
    source: "chess_api",
    format: fmtCount,
    detectorIds: [
      "BLITZ_VS_RAPID_RATING_GAP",
      "CHESS_RATING_TREND_RAPID",
      "CHESS_RATING_TREND_BLITZ",
      "CHESS_RATING_TREND_BULLET",
    ],
  },
  {
    id: "chess_streak",
    domain: "chess",
    name: "Streak (Win/Loss)",
    shortName: "Streak",
    description: "Current and maximum winning/losing streaks",
    unit: "count",
    unitLabel: "games",
    source: "chess_api",
    format: fmtCount,
    detectorIds: ["WIN_STREAK_PATTERNS", "TILT_DETECTION"],
  },
];

// ── Wellbeing Metrics (5, manual) ─────────────────────────────────────────────

const WELLBEING_METRICS: MetricDefinition[] = [
  {
    id: "wellbeing_mood",
    domain: "wellbeing",
    name: "Mood",
    shortName: "Mood",
    description: "How was your overall mood today?",
    unit: "1-10",
    unitLabel: "/10",
    source: "manual",
    inputType: "slider",
    inputConfig: { min: 1, max: 10, step: 1 },
    format: fmtSlash10,
    detectorIds: [
      "MOOD_ENERGY_STAT",
      "MOOD_VOLATILITY",
      "MOOD_DAY_OF_WEEK",
      "MOOD_SLEEP_CORRELATION",
      "CHESS_MOOD_CORRELATION",
      "CHESS_LOSSES_VS_NEXT_DAY_MOOD",
      "MOOD_VS_CHESS_RISK_TAKING",
      "EXERCISE_MOOD_BOOST",
      "CONSISTENCY_VS_MOOD_BASELINE",
    ],
  },
  {
    id: "wellbeing_energy",
    domain: "wellbeing",
    name: "Energy",
    shortName: "Energy",
    description: "How were your energy levels today?",
    unit: "1-10",
    unitLabel: "/10",
    source: "manual",
    inputType: "slider",
    inputConfig: { min: 1, max: 10, step: 1 },
    format: fmtSlash10,
    detectorIds: [
      "MOOD_ENERGY_STAT",
      "ENERGY_DECLINE_PATTERN",
      "BEDTIME_ENERGY_CORRELATION",
      "ENERGY_WORKOUT_CORRELATION",
      "WORKOUT_INTENSITY_VS_NEXT_DAY_ENERGY",
      "CHESS_ENERGY_CORRELATION",
    ],
  },
  {
    id: "wellbeing_stress",
    domain: "wellbeing",
    name: "Stress",
    shortName: "Stress",
    description: "How stressed did you feel today?",
    unit: "1-10",
    unitLabel: "/10",
    source: "manual",
    inputType: "slider",
    inputConfig: { min: 1, max: 10, step: 1 },
    format: fmtSlash10,
    detectorIds: [
      "MOOD_ENERGY_STAT",
      "STRESS_SPIKE_FREQUENCY",
      "STRESS_SLEEP_CORRELATION",
      "WORKOUT_STRESS_CORRELATION",
      "CHESS_STRESS_CORRELATION",
      "STRESS_VS_CHESS_TILT",
    ],
  },
  {
    id: "wellbeing_focus",
    domain: "wellbeing",
    name: "Focus",
    shortName: "Focus",
    description: "How focused were you today?",
    unit: "1-10",
    unitLabel: "/10",
    source: "manual",
    inputType: "slider",
    inputConfig: { min: 1, max: 10, step: 1 },
    format: fmtSlash10,
    detectorIds: [],
  },
  {
    id: "wellbeing_journal",
    domain: "wellbeing",
    name: "Journal Note",
    shortName: "Journal",
    description: "Optional free-text daily note",
    unit: "text",
    unitLabel: "—",
    source: "manual",
    inputType: "text",
    inputConfig: { placeholder: "How was your day?" },
    format: () => "—",
    detectorIds: [],
  },
];

// ── Caffeine Metrics (4, manual) ──────────────────────────────────────────────

const CAFFEINE_METRICS: MetricDefinition[] = [
  {
    id: "caffeine_total_daily",
    domain: "caffeine",
    name: "Total Daily Caffeine",
    shortName: "Caffeine",
    description: "Total caffeine consumed today",
    unit: "mg",
    unitLabel: "mg",
    source: "manual",
    inputType: "number",
    inputConfig: { min: 0, max: 1000, step: 25 },
    format: fmtMg,
    detectorIds: [],
  },
  {
    id: "caffeine_doses",
    domain: "caffeine",
    name: "Number of Doses",
    shortName: "Doses",
    description: "How many separate caffeine intakes today",
    unit: "count",
    unitLabel: "—",
    source: "manual",
    inputType: "stepper",
    inputConfig: { min: 0, max: 10, step: 1 },
    format: fmtCount,
    detectorIds: [],
  },
  {
    id: "caffeine_last_dose",
    domain: "caffeine",
    name: "Time of Last Dose",
    shortName: "Last Dose",
    description: "Clock time of your final caffeine intake",
    unit: "time",
    unitLabel: "—",
    source: "manual",
    inputType: "time",
    inputConfig: {},
    format: fmtTime,
    detectorIds: [],
  },
  {
    id: "caffeine_first_dose",
    domain: "caffeine",
    name: "Time of First Dose",
    shortName: "First Dose",
    description: "Clock time of your first caffeine intake",
    unit: "time",
    unitLabel: "—",
    source: "manual",
    inputType: "time",
    inputConfig: {},
    format: fmtTime,
    detectorIds: [],
  },
];

// ── Hydration Metrics (1, manual) ─────────────────────────────────────────────

const HYDRATION_METRICS: MetricDefinition[] = [
  {
    id: "hydration_water_intake",
    domain: "hydration",
    name: "Water Intake",
    shortName: "Water",
    description: "Total water consumed today",
    unit: "L",
    unitLabel: "L",
    source: "manual",
    inputType: "number",
    inputConfig: { min: 0, max: 8, step: 0.25, placeholder: "litres" },
    format: fmtLitres,
    healthyRange: { min: 2.5, max: 3.5, label: "2.5-3.5L recommended" },
    detectorIds: [],
  },
];

// ── Supplements Metrics (2, manual) ──────────────────────────────────────────

const SUPPLEMENTS_METRICS: MetricDefinition[] = [
  {
    id: "supplements_taken",
    domain: "supplements",
    name: "Supplement Taken",
    shortName: "Taken",
    description: "Whether each supplement was taken today",
    unit: "yes/no",
    unitLabel: "—",
    source: "manual",
    inputType: "toggle",
    inputConfig: {},
    format: (v) => (v > 0 ? "Yes" : "No"),
    detectorIds: [],
  },
  {
    id: "supplements_dose",
    domain: "supplements",
    name: "Supplement Dose",
    shortName: "Dose",
    description: "Amount of each supplement taken",
    unit: "varies",
    unitLabel: "—",
    source: "manual",
    inputType: "number",
    inputConfig: { min: 0, step: 1 },
    format: fmtCount,
    detectorIds: [],
  },
];

// ── Screen Time Metrics (2, manual) ──────────────────────────────────────────

const SCREEN_TIME_METRICS: MetricDefinition[] = [
  {
    id: "screen_time_total",
    domain: "screen_time",
    name: "Total Screen Time",
    shortName: "Screen Time",
    description: "Total hours of screen time today",
    unit: "hours",
    unitLabel: "hrs",
    source: "manual",
    inputType: "number",
    inputConfig: { min: 0, max: 24, step: 0.5, placeholder: "0" },
    format: fmtHours,
    detectorIds: [],
  },
  {
    id: "screen_time_before_bed",
    domain: "screen_time",
    name: "Screen Time Before Bed",
    shortName: "Pre-Bed Screen",
    description: "Hours of screen time in the 2 hours before bed",
    unit: "hours",
    unitLabel: "hrs",
    source: "manual",
    inputType: "number",
    inputConfig: { min: 0, max: 2, step: 0.25, placeholder: "0" },
    format: fmtHours,
    detectorIds: [],
  },
];

// ── Substances Metrics (2, manual) ────────────────────────────────────────────

const SUBSTANCES_METRICS: MetricDefinition[] = [
  {
    id: "substances_alcohol",
    domain: "substances",
    name: "Alcohol (Drinks)",
    shortName: "Alcohol",
    description: "Number of standard drinks consumed today",
    unit: "count",
    unitLabel: "drinks",
    source: "manual",
    inputType: "stepper",
    inputConfig: { min: 0, max: 20, step: 1 },
    format: fmtCount,
    detectorIds: [],
  },
  {
    id: "substances_cannabis",
    domain: "substances",
    name: "Cannabis Use",
    shortName: "Cannabis",
    description: "Whether cannabis was used today",
    unit: "yes/no",
    unitLabel: "—",
    source: "manual",
    inputType: "toggle",
    inputConfig: {},
    format: (v) => (v > 0 ? "Yes" : "No"),
    detectorIds: [],
  },
];

// ── Full registry ─────────────────────────────────────────────────────────────

export const METRIC_REGISTRY: MetricDefinition[] = [
  ...SLEEP_METRICS,
  ...FITNESS_METRICS,
  ...CHESS_METRICS,
  ...WELLBEING_METRICS,
  ...CAFFEINE_METRICS,
  ...HYDRATION_METRICS,
  ...SUPPLEMENTS_METRICS,
  ...SCREEN_TIME_METRICS,
  ...SUBSTANCES_METRICS,
];

// ── Helpers ───────────────────────────────────────────────────────────────────

export function getMetricsByDomain(domain: Domain): MetricDefinition[] {
  return METRIC_REGISTRY.filter((m) => m.domain === domain);
}

export function getMetricById(id: string): MetricDefinition | undefined {
  return METRIC_REGISTRY.find((m) => m.id === id);
}

export function getManualMetrics(): MetricDefinition[] {
  return METRIC_REGISTRY.filter((m) => m.source === "manual");
}

export function getMetricsBySource(
  source: MetricDefinition["source"],
): MetricDefinition[] {
  return METRIC_REGISTRY.filter((m) => m.source === source);
}

export function getMetricsForDetector(detectorId: string): MetricDefinition[] {
  return METRIC_REGISTRY.filter((m) => m.detectorIds.includes(detectorId));
}
